language: java

jdk:
- oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: hekonsek-github
    token:
      secure: "FB2OdzICp57Tt1P6Dsuis8DzyL6PUC/911n9S0VansKVtZcS4EYfKGxPRv0zDPDq6QVg3K45Sj7l3JfNhFDw/Qtl4+kUUQWPEcaFYN5hNfrX7bKJ15AFfanFGhXHHdjLK2tB6HPULDZ91GcrtOVDnZocorQTsuFkMjyTD4/MfLZJt02M/BCAcMmaVSKDeCHSJtJv1EqnCu65/LHQnkM8M2CN/0E7eh50v9m7XvEc0xkqY0ff1Wicd4hHqochWLDVInxXSAojehJIpwRJK6cjwPHKT8MdQGYGFmrMoYrE6sFKgTiJOmZDbHo1K3UpzghvuaU0KlOMMaCx/YUejLo0z0Yym2zCfSd6Ue7jEn/m9A9xjt0k17tm/hLVFUt1O01u6fCw78Ke6m6MSIGRM+tUCOBKzwJjjD06RzXuakXJiVhHv8s8T2UNi2T888b6tLRaarxU1CqZYVSCPtp+r2p2t447CIh1hmVGzzvgopdKApwIgFKNzwmRYtzl1qLX+Ap/w4elAhm5rjVbBPaI/Q18WzJvFYfmuUH/9JPiAg4aIGXBIRvx5wK6iWw0ARXJAI10a8BDZYrYtGtfJIY0F8rmvqyGEKw2X1I7liIvRMbkPDAH0Bad6NWOWBfVauo08E0R5SKruTXpD3AUdoXXinn4grAHS6GciQ1HASRSR78r6XM="

script:
  - mvn clean install sonar:sonar -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)